# Generated by Django 2.2.4 on 2019-08-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_holder', models.CharField(blank=True, default='', max_length=200)),
                ('ticket_number', models.CharField(blank=True, default='', max_length=200)),
                ('flight_number', models.CharField(blank=True, default='', max_length=200)),
                ('destination', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('flight_time', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('ticket_number',),
            },
        ),
    ]
