# Generated by Django 2.2.4 on 2019-08-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Available', 'Available')], default='Available', max_length=10),
        ),
    ]
