# Generated by Django 2.2.4 on 2019-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttickets',
            name='origin',
            field=models.CharField(blank=True, max_length=200, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='flighttickets',
            name='passenger',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name Of Pasenger'),
        ),
        migrations.AlterField(
            model_name='flighttickets',
            name='time',
            field=models.DateTimeField(verbose_name='Date of depature'),
        ),
    ]
